---
title: "test"
author: "Ivan Pavlović, Dino Baralić"
output: html_document
date: "`r Sys.Date()`"
---

```{r}
library(tidyverse)
library(dplyr)
library(readr)
library(stringr)
library(hflights)
library(tidyr)
library(lubridate)
```

```{r}
# UČITAJ PODATKOVNI OKVIR
#putanja <- "C:/Users/dinob/Desktop/OSP/.Osp_projekt/data/ufo_sightings/complete.csv"
putanja <- "../data/ufo_sightings/complete.csv"
df <- read.csv(putanja)

df
```
```{r}

# zamijeni sa NA vrijednostima
df$country[df$country == ""] <- NA
df$state[df$state == ""] <- NA
df$latitude <- as.numeric(df$latitude)

# 'shape' ima puno bespotrebnih naziva
df$shape[df$shape == ""] <- NA
df$shape[df$shape == "unknown"] <- NA
df$shape[df$shape == "other"] <- NA

df

```



```{r}
# FAKORIZACIJA

df$state <- as.factor(df$state)
df$country <- as.factor(df$country)
df$shape <- as.factor(df$shape)

# ili

stupci <- c("state", "country", "shape")
df[, stupci] %>% lapply(factor) -> df[, stupci]

df

```

```{r}

# stavi tip vremenske oznake
df$datetime <- as.POSIXct(df$datetime, format = "%m/%d/%Y %H:%M")
df$date.posted <- as.Date(df$date.posted, format = "%m/%d/%Y")

df

```


```{r}
# PREIMENUJ

names(df)[names(df) == "duration..seconds."] <- "duration_sec"
names(df)[names(df) == "duration..hours.min."] <- "duration_hrs_min"
names(df)[names(df) == "date.posted"] <- "date_posted"
df

```

```{r}
# 1)

# POJAVE NLO-ova PO states-ima
ggplot(df, aes(x = state)) +
  geom_bar(fill = "cyan", color = "black") +
  theme(axis.text.x = element_text(angle = 75, hjust = 1))


```


```{r}
# 2)

# pojave NLO-ova po državama
ggplot(df, aes(x = country)) +
  geom_bar(fill = "chartreuse1", color = "black") +
  theme(axis.text.x = element_text(angle = 75, hjust = 1))

```


```{r}
# 3)

# učestalost viđenja pojedinih oblika

ggplot(df, aes(x = shape)) +
  geom_bar(fill = "coral") +
  theme(axis.text.x = element_text(angle = 80, hjust = 1))



```

```{r}
# 4)

#POPRAVI

# datumska raspodjela uočavanja NLO-a

df2 <- df
df2$year <- year(df2$datetime)

# stavio sam 'year' stupac na drugo mjesto
df2 <- df2 %>% select("datetime", "year", everything()) 
df2


ggplot(df2, aes(x = shape, y = year, color = shape)) +
  geom_point(alpha = 0.6, na.rm = T) +
  scale_x_discrete() +
  scale_y_continuous() +
  theme(axis.text.x = element_text(angle = 80, hjust = 1))


```


```{r}
# 5)

# pojave NLO-a po geo. širinama/dužinama

ggplot(df, aes(x = longitude, y = latitude, color = shape)) +
  geom_point(alpha = 0.6, na.rm = T) +
  scale_x_continuous(name = "dužina") +
  scale_y_continuous(name = "širina")

```


```{r}
# 6)

# prikaz NLO-ova u americi/europi ==> izvuci geo. šir/duž da prikazuje samo ameriku/europu

gAmerika <- ggplot(df, aes(x = longitude, y = latitude, color = shape)) +
  geom_point(alpha = 0.6, na.rm = T) +
  scale_x_continuous(name = "dužina") +
  scale_y_continuous(name = "širina") +
  coord_cartesian(xlim = c(-150, -50), ylim = c(15, 75)) +
  labs(title = "Amerika")

gEuropa <- ggplot(df, aes(x = longitude, y = latitude, color = shape)) +
  geom_point(alpha = 0.6, na.rm = T) +
  scale_x_continuous(name = "dužina") +
  scale_y_continuous(name = "širina") +
  coord_cartesian(xlim = c(-25, 50), ylim = c(25, 75)) +
  labs(title = "Europa")

gAmerika
gEuropa

# POPRAVI NAREDBU ISPOD
#grid.arrange(gAmerika, gEuropa, ncol = 2, nrow = 1)

```

```{r}
# 7)

# raspodjela NLO-a viđenja po mjesecima 

df$month <- month(df$datetime, label = TRUE, abbr = FALSE)

#micanje miseca koji su NA
df_filtered <- df[complete.cases(df$month), ]

ggplot(df_filtered, aes(x = month, fill = factor(month))) +
  geom_bar() +
  scale_x_discrete(labels = month.name) +  
  labs(title = "Raspodjela viđenja NLO-a po mjesecima ", x = "Month", y = "Count") +
  theme_minimal()+theme(axis.text.x = element_text(angle = 45, hjust = 1))


```




```{r}
# 8) Raspodjela vidđenja po danima u tjednu

dow <- df %>%
  mutate(day_of_week = weekdays(as.Date(datetime)))

#micanje dana koji su NA
dow_filtered <- dow[complete.cases(dow$day_of_week), ]

ggplot(dow_filtered, aes(x = day_of_week, fill = day_of_week)) +
  geom_bar() +
  theme_minimal() +
  labs(title = "UFO viđenja po danima u tjednu", x = "Dan u tjednu", y = "Broj viđenja")




```

```{r}
# 9) Top 10 gradova po viđenjima NLO-a


top_cities <- df %>% 
  group_by(city) %>%
  summarise(count = n()) %>%
  arrange(desc(count)) %>%
  top_n(10) 

ggplot(top_cities, aes(x = "", y = count, fill = city)) +
  geom_bar(stat = "identity", width = 1, color = "white") +
  geom_text(aes(label = count), position = position_stack(vjust = 0.5), size = 3) +
  coord_polar("y") +
  theme_void() +
  labs(title = "Top 10 gradova po viđenjima NLO-a", fill = "Grad") +
  scale_fill_brewer(palette = "Set3")  


```


```{r}
# 10) Trend NLO viđenja po desetljećima

df$datetime <- as.POSIXct(df$datetime, format="%m/%d/%Y %H:%M", tz="")

df3 <- df %>%
  mutate(decade = cut(year(datetime), breaks = seq(1900, 2020, by = 10), labels = seq(1900, 2020, by = 10)[-1]))

# makni redove di fali desetljece ili broj viđenja
df3 <- df3 %>%
  filter(!is.na(decade)) %>%
  group_by(decade) %>%
  summarise(sightings_count = n())

# detestljece u factor
df3$decade <- as.factor(df3$decade)

ggplot(df3, aes(x = decade, y = sightings_count, group = 1)) +
  geom_line() +
  geom_point() +
  labs(title = "UFO Sighting Trends Over Decades",
       x = "Decade",
       y = "Number of Sightings") +
  theme_minimal()


```

